name: mada_admin
description: Mada admin dashboard web app.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: ">=3.19.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.0
  data_table_2: ^2.5.15
  fl_chart: ^0.69.0
  shared:
    path: ../../packages/shared

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.staging
    - .env.prod
    - .env.example
